# Generated by Django 4.2.1 on 2024-01-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='projects', verbose_name='image')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'ProyectoIngles',
                'verbose_name_plural': 'ProyectosIngles',
                'ordering': ['-created'],
            },
        ),
    ]
