# Generated by Django 4.2.1 on 2024-01-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectenglish',
            options={'verbose_name': 'ProyectoIngles', 'verbose_name_plural': 'ProyectosIngles'},
        ),
    ]
